# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 232adc2ac358580407fb319409eee9b4adf2865713508966c73b53f6ff1af81dff46fdbb48c4800c94895e480c129f476b11a18fae72520530554e5c857e8421

test:
  secret_key_base: 025ddef24327ff31777806164fb761b06fbd316bbaddb5e08adfb14fac4f0115afcd52ae1e39ac737e4d8dd2944490960fbe3b655715d7c8fd3d8380344b2a7d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
